# Generated by Django 2.0.7 on 2018-07-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=30)),
                ('seen_time', models.DateTimeField()),
                ('ip', models.GenericIPAddressField()),
                ('ap_mac', models.CharField(max_length=30)),
                ('ssid', models.CharField(max_length=100)),
                ('location', models.TextField()),
            ],
        ),
    ]
