# Generated by Django 2.0.7 on 2018-07-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('site', models.CharField(max_length=100)),
                ('news', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='wirelessclient',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
