# Generated by Django 2.0.7 on 2018-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanapi', '0002_auto_20180712_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='wirelessclient',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
